[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Håkan Arvidsson <harvids@gmail.com>"]
edition = "2018"
repository = "https://github.com/hazone/hello-wasm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"